workflows:
  android-release:
    name: Android Release Build
    instance_type: linux
    environment:
      android_signing:
        - release_keystore
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - djmarv_873@hotmail.com
        notify:
          success: true
          failure: true

android_signing:
  release_keystore:
    keystore_reference: release_keystore
    keystore_password: plantapp123
    key_alias: plant_app_key
    key_password: plantapp123
