workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.plantidentifier.app"
        APP_ID: plant-identifier
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - djmarv_873@hotmail.com
